### ISSUE TITLE
Make compatible with R25

### ISSUE THREAD

**Issue by msanity** [mp5gosu/InstanceMan#2]
Hello,
Great plugin!
Do you have any plans to update it to make it compatible with R25?

Thanks!

**Comment by mp5gosu** [comment]
Will do within the next two weeks.

**Comment by mp5gosu** [comment]
Done. See releases or alternatively:
https://www.roberthitzer.de/projects/instanceman/
https://www.core4d.com/ipb/files/file/52-instanceman
